# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksapp', '0002_auto_20170430_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='shortened_url',
            field=models.URLField(null=True),
        ),
    ]
