# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linksapp', '0003_auto_20170430_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortened_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
